stepancheg/rust-protobuf

src/lib/codegen.rs, src/lib/core.rs, src/lib/descriptor.rs, src/lib/error.rs, src/lib/repeated.rs, src/lib/singular.rs, src/lib/stream.rs, src/lib/unknown.rs, src/perftest/perftest_data.rs, src/plugin.rs
Fixed compilation on latest Rust.
One thing you may want to look at is `error.rs`, it needs to implement `Display` which cannot be `derive`d, so I just forwarded to `Debug`.
If you don't know now `Show -> Debug` and `String -> Display`.
There are also a lot of warnings about the new slicing syntax, I can fix those too if you want.
=> Fix compilation

src/lib/maybe_owned_slice.rs, src/lib/repeated.rs
Changed Index trait implementations from &usize to usize. 
Some issues in lib/codegen.rs still remain: rustc says RustType::into doesn't take parameters although the definition is unchanged.
=> Tracking rust nightly

src/lib/codegen.rs, src/lib/core.rs, src/lib/descriptor.rs, src/lib/protobuf.rs, src/lib/rt.rs, src/lib/singular.rs, src/perftest/perftest.rs, src/perftest/perftest_data.rs, src/plugin.rs, src/test/lib.rs, src/test/test.rs, src/test/text_format_test.rs
* make core.rs stable compatible by using generated as_any method
* remove usage of unstable std::iter::Iterator::sum()
* remove Singular[Ptr]Field::as_[mut_]slice()
* remove #![feature(collections)] by copying escape_default() into source
fix #94 \o/
=> remove #[feature(core)] and #![feature(collections)] => stable compliant!

README.md
By default cargo does debug builds, with ```cargo build --release``` target/debug should become target/release.
=> Fixed built protoc-gen-rust's initial path

src/lib/text_format.rs, src/test/text_format_test.rs
Following on from #139. Escaping backslashes allows `protoc --encode` to correctly parse the output produced by rust-protobuf. 0x7f is not strictly necessary, but it matches the output from `protoc --decode` and reads better on the terminal.
I have updated but haven't run the test - it doesn't appear to be hooked up properly?
=> Escape backslashes and 0x7f in bytes text format

benches/stream.rs
In a previous commit I mentioned that I could not determine how to run src/perftest. This commit introduces Rust's builtin-ish benchmark tests to make performance related work somewhat more direct. I got the idea after looking at @siddontang's benchmark code--of which this is an adaptation--on #186.
The motivation here is `CodedInputStream::read` showing up as a CPU hotspot in a program of mine. I'd like to give a go at optimizing it and having `cargo bench` at hand would be convenient.
Out of curiousity I ran these benchmarks to compare the work between c69b1373 and edfc86ac to move to copy_from_slice in write_raw_bytes.
➜  rust-protobuf git:(c69b137) ✗ cargo bench > /tmp/c69b1373
. . .
➜  rust-protobuf git:(edfc86a) ✗ cargo bench > /tmp/edfc86ac
. . .
➜  rust-protobuf git:(edfc86a) ✗ …
=> Introduce benchmark tests

src/lib/error.rs
This enables user of library to use `try!()` macro in function which should return `io::Error`.
~~I should probably bump the version to 1.1.0, right? If yes, let me know and I'll update it right away.~~
~~BTW, I think the doc is outdated, because the converse impl is already there but not in the doc. Could you re-generate it, please?~~
Seems like old version is released. When will be 1.1.0 released?
=> Implemented conversion From<ProtobufError> for io::Error.

src/lib/core.rs
All concrete message types are already `Send + Sync`, but adding it as a
trait bound allows abstract `Message` trait objects (e.g.
`Box<Message>`) to be shared and sent across threads.
The explicit `'static` bound is removed, because `Any` already implies
`'static`.
=> Add Send + Sync bound on Message trait

src/lib/codegen/message.rs, src/lib/core.rs, src/lib/descriptor.rs, src/lib/plugin.rs
These methods are useful when working with abstract Message trait objects.
I believe this commit will fail the `v2/test_basic_pb_1_0_24.rs` test because `Message` will no longer be forward compatible with a `1.0.24`-generated `Message`.  Hopefully that's not considered a breaking change.
=> Add Message::{as_any_mut, into_any}

protobuf/src/buf_read_iter.rs, protobuf/src/stream.rs
=> Implement std::io traits for Coded*Streams

protoc-rust/README.md
I had trouble figuring out/finding documentation on the fact that `protoc-rust` has to be in `[build-dependencies]`, so I figured adding it to the README might make it more clear for other folks.
=> Add documentation on build-dependencies for protoc-rust

protobuf-test/src/common/v2/test_basic.rs, protobuf-test/src/common/v2/test_basic_pb.proto, protobuf/src/error.rs, protobuf/src/rt.rs, protobuf/src/stream.rs
Provide a way to configure recursion limit so invalid messages or deeply nested messages won't lead to stack overflow, which has no way to recover.
=> add recursion limit

protobuf/src/stream.rs
It seems that rust compiler cannot optimize Ok(foo()?) to foo(). Even
when eof() is inlined, Try function might not inlined which causes
function call for every eof() call. This change improves performance
about 15% on some cases.
=> change Ok(foo()?) to foo()

CHANGELOG.md, perftest/vs-cxx/perftest.rs, protobuf-codegen/src/message.rs, protobuf-test/src/test.rs, protobuf/src/core.rs, protobuf/src/descriptor.rs, protobuf/src/lib.rs, protobuf/src/plugin.rs, protobuf/src/reflect/mod.rs, protobuf/src/stream.rs, protobuf/src/types.rs, protobuf/src/well_known_types/any.rs, protobuf/src/well_known_types/api.rs, protobuf/src/well_known_types/duration.rs, protobuf/src/well_known_types/empty.rs, protobuf/src/well_known_types/field_mask.rs, protobuf/src/well_known_types/source_context.rs, protobuf/src/well_known_types/struct_pb.rs, protobuf/src/well_known_types/timestamp.rs, protobuf/src/well_known_types/type_pb.rs, protobuf/src/well_known_types/wrappers.rs
`MessageStatic` is an artifact of very old days of Rust.  It is not
needed today, because function can have `Self : Sized` constraints
today.
This change is backward incompatible.
Closes issue #214
=> Remove `MessageStatic` trait

protobuf-codegen/src/field.rs, protobuf-codegen/src/message.rs, protobuf/src/descriptor.rs, protobuf/src/plugin.rs, protobuf/src/well_known_types/any.rs, protobuf/src/well_known_types/api.rs, protobuf/src/well_known_types/duration.rs, protobuf/src/well_known_types/field_mask.rs, protobuf/src/well_known_types/source_context.rs, protobuf/src/well_known_types/struct_pb.rs, protobuf/src/well_known_types/timestamp.rs, protobuf/src/well_known_types/type_pb.rs, protobuf/src/well_known_types/wrappers.rs
... to generate field accessors for reflection.
This slightly decreases generated code size.
Fixes #228
=> Use non-capturing closure to fn conversion

protobuf-codegen/src/field.rs, protobuf-test/src/common/v2/test_enum_unknown_values_preserved.rs, protobuf-test/src/common/v2/test_enum_unknown_values_preserved_pb.proto, protobuf/src/descriptor.rs, protobuf/src/rt.rs, protobuf/src/well_known_types/api.rs, protobuf/src/well_known_types/type_pb.rs
=> When parsing store unknown enum values in unknown fields

protobuf/Cargo.toml
protobuf uses BufMut which was only added in 0.4.
=> Set bytes requirement to 0.4

protoc-rust/README.md
I added a note in README.md of **protoc-rust** about version of **protobuf**. 
I lost some time to figure out that the problem which I was suffering in #308 was about different versions between **protoc-rust** and **protobuf**. So I added a little note about this issue.
=> Added note about protoc-rust and protobuf version

protoc-rust/README.md
Using `1.5` doesn't compile because
```
customize: Customize {
..Default::default()
}
```
is not supported in `1.5`. Using `1.5` also leads to errors in the generated Rust code.
=> Update version in `Cargo.toml` for example

protobuf-codegen/src/customize.rs
otherwise it doesn't work
Closes #345
=> Customize::_future_options must be public

protoc-rust/src/lib.rs, protoc-rust/src/slashes.rs
=> Fix slashes handling on Windows

protobuf-test/src/common/v2/test_map_simple.rs, protobuf-test/src/common/v2/test_map_simple_pb.proto, protobuf/src/reflect/types.rs
See also: https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/io/coded_stream.h#L1300-L1306
Output verified by 
```
protoc -I proto -I protobuf-test/src/common/v2 --decode TestMap < output.bin
```
=> Fix compute_size(value: &i32) for negative number

protobuf-codegen-pure/README.md
The version suggested here is incompatible with newer rust-protobuf.
Doing this helps lazy people be lazy.
Thanks
=> Latest version in README for easy copy paste.

README.md
This PR updates all code sections in the README.md file to use `rust`/`proto`/`toml` to properly highlight code based on the language in use.
=> Fix syntax highlighting for code sections in README.md

ci/run.sh
Running `ci/run.sh` locally works flawlessly, except for this hardcoded reference to the travis environment.
This PR makes the ci scripts work locally on Linux too - useful for someone just picking up the repo for the first time.
=> ci: use $HOME variable rather than /home/travis

protobuf-codegen/src/code_writer.rs, protobuf-codegen/src/enums.rs, protobuf-codegen/src/field.rs, protobuf-codegen/src/lib.rs, protobuf-codegen/src/message.rs
Notes:
- A few more things could probably be generated.
- Comments containing four spaces are ignored, because rustdoc would try to compile and run those. We could transform those to using ` ```ignore `, but that would require a full markdown parser.
Questions:
- Should this be an option?
Close #402.
=> Add documentation in generated code

protobuf-test/src/common/v2/test_fmt_text_format.rs, protobuf/src/text_format/parse.rs
Fixes #422
This allows me to just use ? on such an error from a function that
returns failure::Error.
In the issue, I also mentioned that ParseErrorWithLoc is a private type.
(It's in a private mod and is never re-exported.) Looks like that
doesn't matter if I just want to use its Error/Display/Debug
implementations, so I didn't change it.
=> implement Error for ParseErrorWithLoc

protobuf-codegen/src/message.rs
Fixes #435: "hidden lifetime parameters in types are deprecated" against generated code when `rust_2018_idioms` is enabled in a project.
With these fixes the sample in #435 was able to build. Did some looking around `message.rs` and didn't find any other cases of missing lifetime parameters.
=> Fix generated code with rust_2018_idioms

protobuf-codegen/src/code_writer.rs, protobuf/src/descriptor.rs, protobuf/src/plugin.rs, protobuf/src/rustproto.rs, protobuf/src/well_known_types/any.rs, protobuf/src/well_known_types/api.rs, protobuf/src/well_known_types/duration.rs, protobuf/src/well_known_types/empty.rs, protobuf/src/well_known_types/field_mask.rs, protobuf/src/well_known_types/source_context.rs, protobuf/src/well_known_types/struct_pb.rs, protobuf/src/well_known_types/timestamp.rs, protobuf/src/well_known_types/type_pb.rs, protobuf/src/well_known_types/wrappers.rs
The original link: https://github.com/Manishearth/rust-clippy/issues/702 was a dead link. Replaced with correct one. https://github.com/rust-lang/rust-clippy/issues/702
=> Fixed dead clippy issue link

protobuf-codegen-pure/src/parser.rs, protobuf-test/src/common/v2/test_service.rs, protobuf-test/src/common/v2/test_service_pb.proto
They can be fully-qualified message type names — not necessarily
just a single identifier.
=> Fix parsing of RPC input and output types

protobuf-codegen/src/field/mod.rs, protobuf-test/src/common/v2/test_serde_derive.rs, protobuf-test/src/common/v2/test_serde_derive_pb.proto
Hi! :wave: 
I've started to use this library to migrate an API from using raw JSON to use Protocol Buffers, and I bumped into a particular case. My JSON document has a couple of optional Map fields, they are not serialized when there are no values on them. I would expect this library to create empty HashMap objects for those fields. That's my understanding on how defaults work on protobuf definitions, but I might be wrong.
I modified the code generator to add `#[serde(default)]` to HashMap fields.
This is an example:
- Given this definition:
```
message TestStruct {
uint64 id = 1;
map<string, string> optional_map = 2;
}
```
and this JSON payload:
```
{"id": "1"}
```
I would expect the deserialization to pass this test:
```
let s: TestStruct = serde_json::from_str(&r#"{"id": …
```
=> Add serde(default) to map fields.

protobuf-test/src/common/v2/test_fmt_json.rs, protobuf/src/json/print.rs
Noticed while converting a message that had a singular field followed repeated field, while looking at the code noticed the same for maps. Was easy to repro with the added test.
=> Added comma before repeated and map fields when printing to json

protoc-rust/README.md
Remove extra comma in readme example
=> Fix protoc-rust readme example

protobuf-codegen/src/message.rs
This will avoid conflict if protocol file also defined a message named Box.
Signed-off-by: bin liu <bin@hyper.sh>
This will fix #491 at v2.14
=> Use full name of Box for generated into_any fn.

protobuf-codegen-pure/src/convert.rs, protobuf-test/src/common/v2/test_reflect.rs, protobuf/src/json/json_name.rs, protobuf/src/json/mod.rs
If not set explicitly, a default JSON name must be computed by the Protobuf compiler. This is required for compatibility with protoc.
The basic gist is that protobuf-codegen-pure is generating incorrect file descriptor data by not setting the JSON name field. In protoc, if the `json_name` option is not provided by the user, it sets the JSON name to the lowerCamelCased name of the field. Not following these rules breaks libraries that do dynamic reflection on the `FileDescriptorSet`, like serde_protobuf.
@stepancheg this is something that was caught by #502 as submitted, though not by the version of the test that's currently on master. If you have suggestions on how to write a test for this, I'd love to hear them. The reason #502 was testing for textually identical output on the file …
=> Always set json name when its default differs from field name

protobuf-codegen-pure/src/convert.rs, protobuf-codegen-pure/src/model.rs, protobuf-codegen-pure/src/parser.rs, protobuf-codegen/src/protobuf_name.rs, protobuf-test/src/common/v2/test_reflect_no_package.rs, protobuf-test/src/common/v2/test_reflect_no_package_pb.proto
A protobuf file with no package is observably different from a protobuf
file with an empty package, since descriptor.proto uses proto2 syntax.
@stepancheg I promise this is the last one for a while! For context, the specific issue I'm having is with serde-protobuf, which has this logic
https://github.com/dflemstr/serde-protobuf/blob/864507a01b85123a6b3bfff6fc665c04ade11b93/src/descriptor.rs#L361-L365
This logic works fine for `FileDescriptorProto`s generated by protoc, which omits the `package` field entirely if the declaration is omitted from the `.proto`, but not for `FileDescriptorProto`s generated by protobuf-codegen-pure, which sets the package field to the empty string if the `package` declaration is omitted from the `.proto`.
One could argue that this is a bug in serde-protobuf, …
=> Omit package in file descriptor proto when empty

protoc-rust/README.md
As far as I can see, the released version already contains the `Codegen` builder.
=> Update protoc-rust readme

protobuf-codegen-pure-test/build.rs, protobuf-codegen-pure/src/lib.rs, protobuf-test-common/src/build.rs, protobuf-test/build.rs
Embed the definitions of rustproto.proto and the well-known type protos
in the protobuf-codegen-pure crate. This ensures that the correct
versions of these proto files are available in every installation of
protobuf-codegen-pure. (Previously, users needed to acquire their own
copy of these protos and configure their include paths accordingly.)
Users can still override these embedded definitions by supplying a file
of the correct name, which will be preferred to the embedded
definitions.
Fix #312.
----
@stepancheg not sure if there's an easier or better way to do this. This was the simplest thing I could come up with.
=> Embed rustproto.proto and WKT protos in protobuf-codegen-pure

protobuf-codegen-identical-test/tests/diff.rs, protobuf-codegen-pure/src/convert.rs
As discussed here: https://github.com/stepancheg/rust-protobuf/pull/505#issuecomment-657289523
The first commit adds the test itself, with some very aggressive normalization rules to work around various mismatches in codegen-pure. The next two commits fix two of the easier mismatches. Details in the individual commit messages.
=> Compare semantic equivalence of FileDescriptorSets generated by codegen-pure and protoc

protobuf-codegen-identical-test/tests/diff.rs, protobuf-codegen-pure/src/convert.rs, protobuf-codegen-pure/src/parser.rs, protobuf/src/text_format/lexer/float.rs, protobuf/src/text_format/mod.rs, protobuf/src/text_format/print.rs
Split out from #510. @stepancheg I don't particularly care about these changes, but they directly fall out from not calling `field.clear_default_value()` in normalize_descriptor.
I'm quite confident that the change to `quote_bytes_to` is valid, as it just adds escaping for single quotes (`'`) like in the C++ version: https://github.com/protocolbuffers/protobuf/blob/f9d8138376765d229a32635c9209061e4e4aed8c/java/core/src/main/java/com/google/protobuf/TextFormatEscaper.java#L79-L81
I'm less sure about the float change (it's hard to say exactly what snprintf will do with `%g` on all platforms: https://github.com/protocolbuffers/protobuf/blob/c0b79c5a398f4eec51ef92784e9d940febdccc52/src/google/protobuf/stubs/strutil.cc#L1245-L1287), but it's definitely true that google/protobuf will render a …
=> Make codegen-pure's field defaults match protoc's

protobuf-codegen-pure-test/Cargo.toml, protobuf-codegen/src/enums.rs, protobuf-codegen/src/message.rs, protobuf-codegen/src/oneof.rs, protobuf-fuzz/Cargo.toml, protobuf-test-common/Cargo.toml, protobuf-test/Cargo.toml, protobuf/Cargo.toml
From local testing I don't think this can land as is because rust-protobuf includes serde_derive directly instead of using the derive feature of serde.
This is intended to resolve #544 and #526.
=> Fully qualify Serialize and Deserialize for serde support.

proto/rustproto.proto, protobuf-codegen/src/customize.rs, protobuf-codegen/src/gen/enums.rs, protobuf-parse/src/proto/rustproto.proto, protobuf/src/rustproto.rs
so as to have serde's rename all for an Enum
Tested with 
```
enum SigProto {
option allow_alias = true;
option (rustproto.serde_rename_all) = "kebab-case";
ip = 0;
pkthdr = 0;
tcp = 1;
tcp_pkt = 2;
tcp_stream = 3;
udp = 4;
icmpv4 = 5;
icmpv6 = 6;
icmp = 7;
sctp = 8;
ipv4 = 9;
ip4 = 9;
ipv6 = 10;
ip6 = 10;
http = 11;
http1 = 12;
http2 = 13;
ftp = 14;
ftp_data = 15;
tftp = 16;
smtp = 17;
tls = 18;
ssh = 19;
imap = 20;
jabber = 21;
smb = 22;
dcerpc = 23;
irc = 24;
dns = 25;
modbus = 26;
enip = 27;
dnp3 = 28;
nfs = 29;
ntp = 30;
ike = 31;
krb5 = 32;
dhcp = 33;
snmp = 34;
sip = 35;
rfb = 36;
mqtt = 37;
template = 38;
template_rust = 39;
rdp = 40;
}
```
=> Adds serde_rename_all extension to enum options

README.md
This feature has been released just looking at 2.25.2, this removes any potential confusion, just speaking for myself, I was almost going to not use it because of reading that this support was not available in a release.
=> Remove "master only" comment in README

protobuf-codegen/src/compiler_plugin.rs
fixes https://github.com/stepancheg/rust-protobuf/issues/625
Not sure how to go about adding a test. If a test is needed I'll need some pointers.
Tested this locally via `cargo install --path .` and then running against a protobuf definition containing an optional field via `protoc --rust_out=out test.proto` where test.proto contained:
```proto
syntax = "proto3";
message Test {
optional string value = 1;
}
```
The generated code includes the following (note the optional field):
```rust
pub struct Test {
// message fields
// @@protoc_insertion_point(field:Test.value)
pub value: ::std::option::Option<::std::string::String>,
// special fields
// @@protoc_insertion_point(special_field:Test.special_fields)
pub special_fields: ::protobuf::SpecialFields,
}
```
=> Signal that plugin supports proto3 optionals

protobuf-parse/Cargo.toml, test-crates/protobuf-codegen-protoc-test/Cargo.toml, test-crates/protobuf-codegen-pure-test/Cargo.toml, test-crates/protobuf-fuzz/Cargo.toml, test-crates/protobuf-test-common/Cargo.toml
`0.*` is essentially the same as `*` since `0.1`, `0.2`, etc. do not have to have a compatible API. Every other crate using logging depends on `0.4`. Do the same here for consistency.
Using `0.*` is also incompatible with `-Z minimal-versions` because it selects `0.1` which does not compile with any post 1.0 rust compiler.
=> Select log version 0.4

protobuf-codegen/src/codegen/mod.rs
Currently `protoc_extra_args` set in the codegen is ignored since it is not passed to the parser. this PR tries to fix  issue https://github.com/stepancheg/rust-protobuf/issues/643
=> Bugfix: use extra args in generator

protobuf-codegen/src/gen/message.rs
Please kindly review. I have detailed the issue - https://github.com/stepancheg/rust-protobuf/issues/675
Note: This feature is not expected to break existing behavior.
=> Customized generation - insert before message (structs)

README.md, protobuf/src/text_format/print.rs
@stepancheg Please kindly review.
fixes https://github.com/stepancheg/rust-protobuf/issues/680 
fixes https://github.com/stepancheg/rust-protobuf/issues/669
=> Fixes unnecessary copy of print_to_string_internal and incorrect prost link in readme.md

protobuf-codegen/src/gen/field/mod.rs, test-crates/protobuf-codegen-protoc-test/src/common/v2/test_repeated_packed.rs, test-crates/protobuf-codegen-protoc-test/src/common/v2/test_repeated_packed_pb.proto
Fixes #704.
Fixes #706.
I wasn't sure how to add tests for either.
For #704, I didn't see a way to distinguish which syntax was being used in a test.
For #706, I didn't see a way to have an invalid proto in a test (the parser fails before you get to the test).
I'm not sure I handled the error correctly, the output looks like:
```
--- stderr
codegen failed: [packed = true] can only be specified for repeated primitive fields
```
As opposed to other errors, that have multiple layers:
```
--- stderr
codegen failed: parse and typecheck
Caused by:
0: using pure parser
1: error in `api.proto`: object is not found by path `tring` in scope `.api.Example`
2: object is not found by path `tring` in scope `.api.Example`
```
There's also no line/column number, but I'm not sure if that's expected.
=> Default to packed for repeated primitives in proto3.

protobuf/src/coded_output_stream/mod.rs
If a message is bigger than the buffer, it will be written directly to the writer, and there was a bug in that case where pos_of_buffer_start was not advanced. This causes later assertions to fail, such as the one in
Message::write_length_delimited_to, which asserts based on total_bytes_written(), which is in turn based on
pos_of_buffer_start.
=> Advance pos_of_buffer_start when writing directly to a writer

protobuf-codegen/src/gen/code_writer.rs, protobuf/src/descriptor.rs, protobuf/src/doctest_pb.rs, protobuf/src/plugin.rs, protobuf/src/rustproto.rs, protobuf/src/well_known_types/any.rs, protobuf/src/well_known_types/api.rs, protobuf/src/well_known_types/duration.rs, protobuf/src/well_known_types/empty.rs, protobuf/src/well_known_types/field_mask.rs, protobuf/src/well_known_types/source_context.rs, protobuf/src/well_known_types/struct_.rs, protobuf/src/well_known_types/timestamp.rs, protobuf/src/well_known_types/type_.rs, protobuf/src/well_known_types/wrappers.rs
Presence of this lint in generated rust files causes warnings on beta.
(I use -Dwarnings in CI so noticed early.)
See https://github.com/rust-lang/rust/pull/126018 for rationale. TL;DR: it's a useless lint.
=> Remove use of box_pointers lint

protobuf/build.rs
Fixes https://github.com/stepancheg/rust-protobuf/issues/735
The alternative would have been to depend on https://crates.io/crates/rustc_version, but that would have been a larger change.
=> apply RUSTC_WRAPPER when querying rustc version

protobuf-parse/src/pure/convert/option_resolver.rs, protobuf-parse/src/pure/model.rs, protobuf-parse/src/pure/parser.rs, protobuf-support/src/lexer/tokenizer.rs
This adds support for repeated fields in constants. Until now the following was failing with a parsing error:
```protobuf
optional uint64 my_field = 1 [ (my_option) = { my_option_repeated_field: ["foo", "bar"] } ];
```
This is valid for `protoc` and it's covered in the specification, but the parser wasn't accepting the `["foo", "bar"]`
syntax for assigning a value to the repeated field.
Some refactoring was required to implement this. Particularly, the functions `option_value_field_to_unknown_value`
and `option_value_message_to_unknown_value`, which returned `UnknownValue`, now receive a mutable `UnknownFields`
and add new fields to it. These function where renamed to more appropriate names.
Additionally, this fixes an issue while parsing constant messages that use commas or semicolons as …
=> feat: add support for repeated fields in constants

CHANGELOG.md, protobuf/src/coded_input_stream/mod.rs
This avoids the denial of service issue as described on:
https://github.com/stepancheg/rust-protobuf/issues/749
https://rustsec.org/advisories/RUSTSEC-2024-0437
=> Apply depth limit to unknown groups
