.travis.yml
install-protobuf.sh

Use latest protobuf and prune travis config

---

install-protobuf.sh

@stepancheg might speed up the build. 8m before this change

Travis container build

---

src/lib/codegen.rs

@stepancheg missed when you grabbed my branch

Remove unused attribute

---

src/lib/codegen.rs
src/lib/descriptorx.rs
src/lib/error.rs
src/lib/hex.rs
src/lib/maybe_owned_slice.rs
src/lib/protobuf.rs
src/lib/reflect/mod.rs
src/lib/repeated.rs
src/lib/rt.rs
src/lib/stream.rs
src/lib/text_format.rs
src/lib/unknown.rs

* remove deprecation warnings
* remove the need of box_patterns
* remove the need of str_char
* remove the need of convert

On the way to stable

---

src/lib/rt.rs

Fallout from https://github.com/rust-lang/rust/commit/97f24a85965c3c51a2c18be029091ae52bbd7920

`AdditiveIterator` has been removed

---

src/lib/stream.rs

This commit removes the use of copy_nonoverlapping in favor of
copy_from_slice as per the TODO comment left in the source code.
The stable version of this writing is 1.14.0.
I am unsure how to run the performace testing code in src/perftest
and do not have a comparision to offer.
Signed-off-by: Brian L. Troutwine <blt@postmates.com>

Move away from unsafe copy_nonoverlapping in write_raw_bytes

---

src/lib/buf_read_iter.rs
src/test/common/test_basic.rs

Fixes crashing assert in bit_read_iter

---

README.md

Fix links to files that broken because of reorganizing code.

Fix links in the main README.md

---

protobuf/src/chars.rs

Just like `Vec<u8>` to `Bytes`,  impl `From<String>` for `Chars` would be handy.

convert String to Chars

---

protobuf/src/plugin.rs
protobuf/src/rustproto.rs

Some files changed due to 112455f303e8f9f038c9e44ff2613e44ccffffe3.

Rebuild generated files

---

protoc/src/lib.rs

Better error message when protoc is not found

---

protobuf-test/src/common/v2/test_ident_pb.proto
protobuf/src/descriptorx.rs

Escape message and enum names which are rust keywords

---

protobuf-test/src/common/v2/test_ident_pb.proto
protobuf/src/codegen/enums.rs
protobuf/src/descriptorx.rs

Escape rust name in enum value variants

---

protobuf-codegen/src/code_writer.rs
protobuf-codegen/src/field.rs
protobuf-codegen/src/message.rs

Codegen refactoring

---

protoc-rust/README.md

protoc-rust: Update build.rs example in README.md

---

.travis.yml
ci/install-protobuf.sh

instead of full protobuf from sources

Download prebuilt protoc on Windows

---

ci/run.sh
protoc/src/lib.rs

Add docs for `protoc`.
See #231

protoc: enforce deny(missing_docs)

---

ci/run.sh
protoc/src/lib.rs

protoc: enforce deny(missing_docs) [backport]

---

protobuf/src/misc.rs

Map some of well known types to Rust equivalents.

---

protobuf-codegen/src/rust.rs

Closes #459 stepancheg/grpc-rust#167
Signed-off-by: imtsuki <me@qjx.app>

Add async/await to RUST_KEYWORDS

---

FAQ.md

The protobuf::parse_from_bytes is deprecated.

Update deserialization FAQ

---

protobuf-codegen-pure/src/lib.rs

- just a veeeeery small fix in the documentation

doc: fix documentaion

---

README.md
protobuf-codegen/README.md
protoc/README.md

There are some links that are stale or broken, update the links. Let me know if the fix reflects the reality

Fix broken link

---

protobuf/src/coded_output_stream.rs
protobuf/src/misc.rs
protobuf/src/varint.rs

See the explanations and discussion in #592.

Fix invalid aliasing and uninit memory in CodedOutputStream

---

protobuf/README.md
protobuf/src/lib.rs

Fixed a minor mistake on README

---

protobuf/README.md
protobuf/src/lib.rs

Just a PR to add some simple installation instructions as I was a bit confused when I first tried using this crate.

Add install section to README.md
